---
- name: Create Multiple Palo Alto Address Objects
  hosts: pa_fw01
  connection: local
  gather_facts: false

  vars:
    # 'panos_provider' inherits values from AAP Machine Credentials
    panos_provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"

    # List of multiple address objects to create
    firewall_objects:
      - { name: "Server_Web_01", value: "10.0.1.50", type: "ip-netmask", desc: "Main Web Server" }
      - { name: "Server_DB_01", value: "10.0.1.60", type: "ip-netmask", desc: "Database Server" }
      - { name: "VPN_Client_Range", value: "192.168.50.10-192.168.50.100", type: "ip-range", desc: "Client VPN Pool" }
      - { name: "Update_Service_FQDN", value: "updates.paloaltonetworks.com", type: "fqdn", desc: "PAN-OS Updates" }

  tasks:
    - name: Create Address Objects
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ panos_provider }}"
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        address_type: "{{ item.type }}"
        description: "{{ item.desc | default(omit) }}"
        state: "present"
      loop: "{{ firewall_objects }}"
      loop_control:
        label: "{{ item.name }}" # Cleans up AAP console output by only showing the object name

