- name: Configuration Deployment
  hosts: paloalto
  connection: httpapi
  gather_facts: false

  tasks:
    - debug:
        msg:
          - "user={{ ansible_user | default('MISSING') }}"
          - "password={{ ansible_password | default('MISSING') }}"
