- name: TEST NXOS COMMAND
  hosts: Nexus9300
  gather_facts: no


  tasks:


    - name: configure bgp 
      nxos_config:
        lines:
          - show version
        output: text

          
          
        


          
        
      